---
- hosts: 127.0.0.1
  become: true
  tasks:
    - name: Install OpenJDK 11     
      apt: name=openjdk-11-jdk state=present
    
    - name: Install Maven
      apt: name=maven state=present 
    
    - name: Install zip and unzip
      apt:
        name: 
          - zip
          - unzip
        state: present      
   
    - name: Ensure gradle directory exists
      file:
        path: /opt/gradle
        state: directory
   
    - name: Download and install Gradle
      unarchive:        
        src: https://services.gradle.org/distributions/gradle-5.6.2-bin.zip
        dest: /opt/gradle
        remote_src: yes        
   
    - apt: update_cache=yes
    
    - name: Setup environment variables      
      shell: |
        echo "export GRADLE_HOME=/opt/gradle/gradle-5.6.2  
        export PATH=\${GRADLE_HOME}/bin:\${PATH}" > /etc/profile.d/gradle.sh
        
    - name: Make the script executable       
      shell: chmod +x /etc/profile.d/gradle.sh
    - name: Load the environment variables   
      shell: source /etc/profile.d/gradle.sh
      args:
        executable: /bin/bash