---
- hosts: 127.0.0.1
  become: true
  tasks:
    - name: Install OpenJDK 11     
      apt: name=openjdk-11-jdk state=present
    - apt: name=maven state=present    
    - apt: name=zip  state=present
    - apt: name=unzip state=present
    - name: Download Gradle
      shell: wget https://services.gradle.org/distributions/gradle-5.6.2-bin.zip -P /tmp 
    - name: Extract the zip file  
      shell: unzip -d /opt/gradle /tmp/gradle-5.6.2-bin.zip
    - apt: update_cache=yes
    - name: Setup environment variables      
      shell: |
        echo "export GRADLE_HOME=/opt/gradle/gradle-5.6.2  
        export PATH=\${GRADLE_HOME}/bin:\${PATH}" > /etc/profile.d/gradle.sh
        
    - name: Make the script executable       
      shell: chmod +x /etc/profile.d/gradle.sh
    - name: Load the environment variables   
      shell: source /etc/profile.d/gradle.sh
      args:
        executable: /bin/bash