---
- hosts: 127.0.0.1
  become: true
  tasks:
    - name: Update apt packages      
      apt:        
        update_cache: yes
    - apt: name=python state=present
    - apt: name=python-dev state=present
    - apt: name=python-pip state=present
    - apt: name=python-setuptools state=present
    - apt: name=python-tk state=present
    - apt: name=ipython state=present   
    - apt: name=python3 state=present
    - apt: name=python3-dev state=present
    - apt: name=python3-pip state=present
    - apt: name=python3-setuptools state=present
    - apt: name=python3-tk state=present
    - apt: name=ipython3 state=present
    - apt: name=build-essential state=present
    
    - name: Installing python packages      
      become_user: codio
      pip:
        name: numpy, scipy, matplotlib
        extra_args: --user
        
    - name: Installing python packages           
      pip:
        name: pycodestyle, pygame
        