---
- hosts: 127.0.0.1
  become: true
  tasks:
    - apt: update_cache=yes  
    
    - name: Install python2, python3, build-essential
      apt:
        name:
          - python
          - python-dev
          - python-pip
          - python-setuptools
          - python-tk
          - ipython
          - python3
          - python3-dev
          - python3-pip
          - python3-setuptools
          - python3-tk
          - ipython3
          - build-essential
        state: present
        update_cache: yes
    
    - name: Installing python libs     
      become_user: codio
      pip:
        name: numpy, scipy, matplotlib
        extra_args: --user
        
    - name: Installing python packages           
      pip:
        name: pycodestyle, pygame
        