---
- hosts: 127.0.0.1
  sudo: true
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
    - apt: name=build-essential state=present
    - apt: name=manpages-dev state=present    
    - apt: name=gdb state=present
    - apt: name=bison state=present
    - apt: name=autoconf state=present
    - apt: name=automake state=present
    - apt: update_cache=yes
    
   